### ISSUE TITLE
Git hook not working on Python 3.6

### ISSUE THREAD

**Issue by codefo** [klen/pylama#111]
Because on `3.6` this list:
https://github.com/klen/pylama/blob/2b24137fe38d2e7c1a9c7bb54edade619e27af60/pylama/hook.py#L36
contains bytes (`b'some/paths/to/files.py'`) not strings. 

So that check always fails:
https://github.com/klen/pylama/blob/2b24137fe38d2e7c1a9c7bb54edade619e27af60/pylama/main.py#L38 
because 
https://github.com/klen/pylama/blob/2b24137fe38d2e7c1a9c7bb54edade619e27af60/pylama/lint/__init__.py#L14
returns `False`.

I think simplest fix is change mapper to 
`candidates = list(map(lambda file: file.decode('utf-8'), files_modified))`
(but I'm not sure about that is it correct for `2.x`)

**Comment by klen** [comment]
@codefo Thank you for the report.

**Comment by codefo** [comment]
Cool, thank you for your work!
