### ISSUE TITLE
How to use "pylama --hook" in the git hooks

### ISSUE THREAD

**Issue by lucassouto** [klen/pylama#118]
Hello guys. I started using pylama and wanted to know how to use git hooks, since I did not find anything that would clarify this.

**Comment by Pawamoy** [comment]
I guess you want to run Pylama before each commit?

A basic solution would be to write this in `.git/hooks/pre-commit`:

```bash
#!/bin/bash

# make sure pylama is available
command -v pylama &>/dev/null || exit 0

# run pylama on the whole repository
pylama "$(git rev-parse --show-toplevel)"
```


https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

**Comment by lucassouto** [comment]
So this approach had already done in some projects to use hooks in pre-push, but I realized when I started using pylama that it has a command in the CLI which is `pylama --hook` which creates a pre-commit file in` .git/hooks/ `, only that it does not make the verification as in the case of your code above.

**Comment by lucassouto** [comment]
Looking at the `hook.py` from pylama I saw that it executes this code: `git diff-index --cached --name-only HEAD`

**Comment by Pawamoy** [comment]
Oh, I didn't know about that `--hook` option. The `git diff-index` is here to run pylama on files that have been modified only (better than running pylama on all the repo each time).

**Comment by lucassouto** [comment]
I changed the title to clear the doubt, thanks

**Comment by mzfr** [comment]
@lucassouto You can use it like `pylama --hook <path to the folder>`
Now the path to the folder depends upon you if you want to add git hook then path will have to be any git repository and if you want hook for mercurial then path to the mercurial repo.

To understand better take a look at [hook.py#L100](https://github.com/klen/pylama/blob/develop/pylama/hook.py#L100)

**EXAMPLE**
`pylama --hook /home/pylama`

you'll get output like:
```
Git hook has been installed.
```
