### ISSUE TITLE
Good to see you back!

### ISSUE THREAD

**Issue by diraol** [klen/pylama#130]
Hi @klen , it is nice to see you back working on this project! =)

Me and @fmv1992 worked on pylama (in order to keep it working for `python-mode`) on a fork (https://github.com/fmv1992/pylama/) If you want to get the changes from there, feel free to do it! We mainly worked on small improvements and fixes, there shouldn't have major changes over there, as far as I remember.

(And feel free to close this issue too as soon as you get this message!)

If you want me to do a "PR" from there to here, let me know.

**Comment by fmv1992** [comment]
@diraol ,

I'm sorry for the late reply! I usually read the messages on my email but rarely reply to them : )

As always, I'm glad to see our python-mode related projects alive.

I wish you both the best ; )
