### ISSUE TITLE
latest version seems to ignore config sections 

### ISSUE THREAD

**Issue by NoobSkywalker** [klen/pylama#132]
using the latest commit i suddenly get all "line too long" errors although i have the current config:
[pylama:pep8]
max_line_length = 120

and even if i add the rule E501 to ignore on that section it does not working so i assume something went wrong in the latest config parsing changes.

**Comment by klen** [comment]
@NoobSkywalker pep8 has been renamed into pycodestyle library. So please use 

[pylama:pycodestyle]
max_line_length = 120

instead
