### ISSUE TITLE
Pylama and Pylava projects should merge maybe

### ISSUE THREAD

**Issue by cscutcher** [klen/pylama#141]
After issue #123 was open for such a long time and the seeming abandonment of the pylama repo the pylava project was forked off of this repo. 

No judgement on yourself @klen , you've put together a great project and we are all aware other commitments can get in the way of open source stuff! 

That being said, now that you're back on the scene, perhaps it'd be good to see pylama and pylava merge back into a single project again under shared stewardship to combine efforts and reduce confusion for new users. 

Not being a member of either projects teams I'm opening a ticket in both repos to advocate you guys getting in touch with each other. Before #123 was fixed I moved a lot of my stuff over to pylava which wasn't too painful but I'd like to avoid having to keep shifting back and forth in the future.

It may be the case that you guys are already talking, but it'd be nice to know what the situation is. 

Many thanks for all the hard work.

**Comment by klen** [comment]
Have nothing against it.
