### ISSUE TITLE
Radon output is not consistent with other output.

### ISSUE THREAD

**Issue by xNinjaKittyx** [klen/pylama#164]
Radon output with pylint format does not output consistently with others.

```
file:line: [C] C901 'someobject' is too complex (14) [mccabe]
```
vs
```
file:line: [R] R701: someobject is too complex 13 [radon]
```

It's really minor, but is it possible to get rid of the colon after the error code? pyflakes, pycodestyle, pylama, are all following the former.

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed.
