### ISSUE TITLE
Inconsistent output of "W0612 local variable '%s' is assigned to but never used [pyflakes]"

### ISSUE THREAD

**Issue by pacanukeha** [klen/pylama#165]
I have a project with two files. In one I have

except Exception as ex:
   log.exception("text")

In the other I have

except Exception as ex:
    log.exception("text")
<snip>
except Exception as ex:
    log.error("some stuff goes here with %s", ex.message)

The first file complains about W0612.
The second file does not.

Personally I don't think that the exception declaration should trigger the warning, without it we get a bare exception warning.
I also think it is a bit confusing since I think it is supposed to be F841 ( PEP 8 doesn't define W612 per https://pep8.readthedocs.io/en/latest/intro.html#error-codes)
Assuming we want to throw the error and use that error code, it looks like it is still a bug for the first except Exception as ex line to not throw the warning.

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed.
