### ISSUE TITLE
If pylint is incorrectly configured, pylama do not fails and do not report any error

### ISSUE THREAD

**Issue by Djailla** [klen/pylama#166]
Hello,

Here is my issue.

In a pylama.ini, I did setup pylint and use the `ignore` prefix instead of `disable`.
Then pylama does not report errors AND pylint is no longer reporting any errors as it's not run :(

Is there a way to improve this behavior and report a warning when the configuration is not valid ?

Here is the configuration exemple :

Hello,

Here is my issue.

In a pylama.ini, I did setup pylint and use the `ignore` prefix instead of `disable`.
Then pylama does not report errors AND pylint is no longer reporting any errors as it's not run :(

Is there a way to improve this behavior and report a warning when the configuration is not valid ?

Here is the configuration exemple :

```[pylama]
format = pylint
linters = pycodestyle,pydocstyle,pylint
skip = {toxworkdir}/*,build/*,.tox/*,env*/*,.env*/*,venv*/*,.venv*/*,.eggs/*,*/migrations/*


[pylama:pylint]
ignore = missing-docstring,locally-disabled,line-too-long,no-member,too-few-public-methods,no-self-use,no-init


[pylama:pydocstyle]
ignore = D100,D101,D102,D103,D104,D105,D106,D107,D200,D203,D208,D213,D401,D404,D406,D407,D413
match_dir = (?!(test_|compatibility_dsl)).*\.py


[pylama:pycodestyle]
ignore = E731,W503,W504,W606
max_line_length = 79```

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed.
