### ISSUE TITLE
Specify line length for all linters.

### ISSUE THREAD

**Issue by hardkrash** [klen/pylama#17]
I would like to set my line length to 120 as opposed to 79.

It seems that pylama has no global option to specify line length config.
When running pep8 it is ignoring the global pep8 config file.

**Comment by sunjay** [comment]
For anyone who gets here from Google, the correct syntax is now:

```ini
[pylama:pep8]
max_line_length=100
```

Source: https://github.com/klen/python-mode/issues/559
