### ISSUE TITLE
PyPI package installs global tests-package

### ISSUE THREAD

**Issue by Fronkan** [klen/pylama#170]
The "tests" package is installed together with the project when installing from PyPI. My guess is that it is not excluded in the setup.py. You can reproduce this by creating a new virtual environment and activating it. Then run
`python -c "import tests"`
Which causes an "module not found" error.
After installing pylama, (pip install pylama)
`python -c "import tests`
returns nothing. Which means tests it found a module named tests

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed.
