### ISSUE TITLE
Pylama example with pylint not working

### ISSUE THREAD

**Issue by PeriGK** [klen/pylama#176]
Hi,

I am trying to use the example of the documentation but it doesnt seem to find pylint. I have installed pylama_pylint.

Any ideas?

> [pylama]
format = pylint
skip = */.tox/*,*/.env/*
linters = pylint,mccabe
ignore = F0401,C0111,E731

```
 pylama myfile.py -l pylama_pylint
WARNING:root:Linter `pylama_pylint` not found.
18:31 $ pylama myfile.py -l pylint
WARNING:root:Linter `pylint` not found.
```

Any ideas?

Thanks,
Periklis

**Comment by klen** [comment]
Please ensure that you have installed pylint. `pylama myfile.py -l pylama_pylint`
