### ISSUE TITLE
mccabe cannot be configured

### ISSUE THREAD

**Issue by jameswilliams1** [klen/pylama#178]
There is no documentation on how to setup mccabe when using pylama. Anyone would expect something like the following inside `setup.cfg`:
```toml
[pylama:mccabe]
max-complexity = 15
```
But on adding this I still get the error (obfuscated):
```sh
scrapers/***/scraper.py:62:1: C901 '***' is too complex (12) [mccabe]
```
I assume the default is 10 due to this, but the override is not being picked up.

**Comment by alberteikelenboom** [comment]
I have the same issue. I tried [pylama:flake8] as well, but no success. I have to say the default value of 10 is a reasonable value, but still it would be nice to configure it.

**Comment by alberteikelenboom** [comment]
I checked the python code:
https://github.com/klen/pylama/blob/develop/pylama/lint/pylama_mccabe.py

And I saw:
:return list: List of errors.
        """
        tree = compile(code, path, "exec", ast.PyCF_ONLY_AST)

        McCabeChecker.max_complexity = int(params.get('complexity', 10))
        return [
            {'lnum': lineno, 'offset': offset, 'text': text, 'type': McCabeChecker._code}
            for lineno, offset, text, _ in McCabeChecker(tree, path).run()

That inspired me to try:
[pylama:mccabe]
complexity = 10

And it worked!

**Comment by jameswilliams1** [comment]
> 
> 
> I checked the python code:
> https://github.com/klen/pylama/blob/develop/pylama/lint/pylama_mccabe.py
> 
> And I saw:
> :return list: List of errors.
> """
> tree = compile(code, path, "exec", ast.PyCF_ONLY_AST)
> 
> ```
>     McCabeChecker.max_complexity = int(params.get('complexity', 10))
>     return [
>         {'lnum': lineno, 'offset': offset, 'text': text, 'type': McCabeChecker._code}
>         for lineno, offset, text, _ in McCabeChecker(tree, path).run()
> ```
> 
> That inspired me to try:
> [pylama:mccabe]
> complexity = 10
> 
> And it worked!

Good spot! I'll try and add a pr at some point if you haven't already.

**Comment by alberteikelenboom** [comment]
pr , personal record? No I didn't. So please do so, whatever it is.

**Comment by klen** [comment]
fixed, thank you

**Comment by kakoma** [comment]
Might be a pylama version issue but I used this for version 8.3.8. The other solution didn't work:

```
[pylama:mccabe]
max-complexity = 12
```
