### ISSUE TITLE
 pylama's pytest plugin calling deprecated methods

### ISSUE THREAD

**Issue by cerealkill** [klen/pylama#184]
Hi, I am having this warning with pylama's pytest plugin.

venv/lib/python3.7/site-packages/pylama/pytest.py:43: 41 tests with warnings 
PytestDeprecationWarning: direct construction of PylamaItem has been deprecated, please use PylamaItem.from_parent
    return PylamaItem(path, parent)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

**Comment by cjkirk09** [comment]
With the new release of pytest 6.0.0, running pytest with `--pylama` breaks with an error

`../../../.virtualenvs/venv/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../.virtualenvs/venv/lib/python3.6/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../.virtualenvs/venv/lib/python3.6/site-packages/pluggy/manager.py:87: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
../../../.virtualenvs/venv/lib/python3.6/site-packages/pylama/pytest.py:43: in pytest_collect_file
    return PylamaItem(path, parent)
../../../.virtualenvs/venv/lib/python3.6/site-packages/_pytest/nodes.py:95: in __call__
    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)
E   pytest.PytestDeprecationWarning: Direct construction of PylamaItem has been deprecated, please use PylamaItem.from_parent.
E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
`

**Comment by n0nSmoker** [comment]
Any updates?

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed in the latest version (8.0.4)
