### ISSUE TITLE
PEP 257 D402 triggers despite whitespace between function name and bracket.

### ISSUE THREAD

**Issue by Viech** [klen/pylama#186]
The following code gives me a `D402` (first line should not be the function's "signature"):
```python
    def reshuffled(self, permutation="ikjl", dimensions=None, order="C"):
        """Return the reshuffled (or realigned) expression.

        […]
        """
```
I feel that the whitespace should be sufficient to not trigger the signature detection.

**Comment by klen** [comment]
Thank you for the feedback. The issue needs to be forwarded to pydocstyle project.
