### ISSUE TITLE
test_eradicate fails with AttributeError: 'NoneType' object has no attribute 'run'

### ISSUE THREAD

**Issue by sbraz** [klen/pylama#190]
Hi,
Since eradicate v2.0, `tests/test_linters.py::test_eradicate` fails with:
```
    def test_eradicate():
        eradicate = LINTERS.get('eradicate')
>       errors = eradicate.run('', code="\n".join([
            "#import os",
            "# from foo import junk",
            "#a = 3",
            "a = 4",
            "#foo(1, 2, 3)",
        ]))
E       AttributeError: 'NoneType' object has no attribute 'run'

tests/test_linters.py:16: AttributeError
```

The commit which broke it is myint/eradicate@7ac22160d80f296c4c74b40b499c56f3549f208b (merged as myint/eradicate@6ca1b944d60f39691a553b3da346221da769b2a7).

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed in the latest version (8.0.4).
