### ISSUE TITLE
AttributeError during test at test_linters.py line number 16.

### ISSUE THREAD

**Issue by asellappen** [klen/pylama#191]
Adding arch power on (ppc64le) to support this package and facing prolbem for both cpu arch arm64/ppc64le as below in the test 

test_linters.py

=================================== FAILURES ===================================
________________________________ test_eradicate ________________________________
    def test_eradicate():
        eradicate = LINTERS.get('eradicate')
>       errors = eradicate.run('', code="\n".join([
            "#import os",
            "# from foo import junk",
            "#a = 3",
            "a = 4",
            "#foo(1, 2, 3)",
        ]))
E       AttributeError: 'NoneType' object has no attribute 'run'
tests/test_linters.py:16: AttributeError
===================== 1 failed, 19 passed in 1.25 seconds ======================
ERROR: InvocationError for command /home/travis/build/asellappen/pylama/.tox/py27/bin/py.test tests -s (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
The command "tox" exited with 1.

Can you look at this ?

**Comment by asellappen** [comment]
sorry ,cpu arch referred are amd64/ppc64le,  not arm64/ppc64le .

Ps refer jobs https://travis-ci.com/github/asellappen/pylama/jobs/443553155

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed in the latest version (8.0.4).
