### ISSUE TITLE
pylama.ini skip option no effect (disabled by TODO note)

### ISSUE THREAD

**Issue by Ka55i0peia** [klen/pylama#193]
Skipping files in `pylama.ini` at global section, like in the following sample snippet, has no effect. The file is passed to linter anyway (and linter errors getting displayed).

```
[pylama:__main__.py]
skip = 1
```

I watched down the code and found it can not work due to this commit: 29f93e905196d76cb3f87e4c5f7d2852cbdfa89b . The `skip` parameter will be overwriten set hard coded to `False` and there is a `TODO` note. That's okay, to quick fix a bad side behavior, but I was missing an issue for this TODO!?

@fmv1992 : Is there an Issue? Can you say something about the "erratic behavior for linters"?

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed in the latest version (8.0.4).
