### ISSUE TITLE
Send arguments to linter through command line

### ISSUE THREAD

**Issue by GodefroyClair** [klen/pylama#194]
Hi,
If I want to pass some arguments to a tool of _Pylama_ (e.g _PycodeStyle_), is there an alternative to creating a config file (_pylama.ini_ or another) ?
For example, if I want to pass the argument "--max-line-length" to _pycodestyle_, can do it using a command line option of _Pylama_?
The reason is that using _Vim_ & _CoC-Python_, I am starting to have too many config files to check (_coc-settings_, _pylama_, _pyright_...). As CoC has an option to pass arguments to pylama ("python.linting.pylamaArgs"), I could centralize all my pylama options in my CoC config file.
Thanks!

**Comment by klen** [comment]
@GodefroyClair Thank you for the feedback. It's possible from version 8.2.0
