### ISSUE TITLE
Breaking changes `check_path` vs `check_paths`. Docs still out of date.

### ISSUE THREAD

**Issue by triorph** [klen/pylama#202]
Looks like commit @4e58c575 changed the function "check_path" to be "check_paths" with slightly different parameters required.

Unsure if this was intentional or not,  but the README.md ( https://github.com/klen/pylama#run-pylama-from-python-code ) still says check_path, which makes it difficult to find the correct syntax.

**Comment by klen** [comment]
@triorph Thank you for the report. I've restored the old method `check_path` (with a depreciation warning) and updated the README.
