### ISSUE TITLE
[>=8.2.1] Options file is ignored with --options argument

### ISSUE THREAD

**Issue by sawatsky** [klen/pylama#205]
In `pylama>=8.2.1`, the `--options` argument seems to be ignored. The [C] errors are being raised, even though I have ignored them in my options file, `setup.cfg`.

Command:
```bash
pylama . --options setup.cfg
```

setup.cfg:
```txt
[pylama:tests/*.py]
ignore = C0114,C0115,C0116
```

The issue appears in the latest pylama (8.3.3) as well.

In `pylama<=8.2.0`, the command and setup.cfg file work perfectly.

**Comment by klen** [comment]
@sawatsky I couldn't repeat.

`setup.cfg`
```ini
[pylama]
linters = pylint

[pylama:test.py]
ignore = C0114,C0115,C0116
```
`test.py`
```python
import sys
```
Result:
```shell
$ pylama test.py --options setup.cfg
test.py:1:1 W0611 Unused import sys [pylint]
```

`C0114` is ignored, maybe you may provide more info to debug?

**Comment by klen** [comment]
@sawatsky Please try the latest version (8.3.1). Thank you for the report 🙏
