### ISSUE TITLE
Mercurial hooks fails when working with virtualenvs

### ISSUE THREAD

**Issue by MrShark** [klen/pylama#22]
I have a mercurial installed globaly and pylama in a virtualenv.
When installing mercurial hooks they fail since mercurial can't import the hook and fails.
##

**Comment by mzfr** [comment]
@MrShark They seem to work now. Can you provide some other information.

**Comment by MrShark** [comment]
Sorry fo very late answer 🤪

I no longer use mercurial (or pylama), so can't provide more info. Will close.
