### ISSUE TITLE
settings overwriting eachother

### ISSUE THREAD

**Issue by mruwnik** [klen/pylama#34]
I have the following lines in my pylama.ini file
[pylama:*/**init**.py]
ignore = W0611

[pylama:bla/**init**.py]
ignore = E402,W0611

On one machine this works as expected (W0611 is ignored for all **init**.py files, while bla/**init**.py also ignores E402). But when the same code is checked on a different machine, with the same pylama version, it causes E402 errors to be found for bla/**init**.py.
##

**Comment by trojkat** [comment]
@mruwnik, how about changing the order:
```
[pylama:bla/init.py]
ignore = E402,W0611

[pylama:*/init.py]
ignore = W0611
```

**Comment by mzfr** [comment]
@mruwnik any updates on this issue ?

**Comment by mruwnik** [comment]
I can't remember. It was 2 years ago. I haven't had that problem since then, though.

**Comment by mzfr** [comment]
Okay since you haven't had any issue and neither did someone else reported something similar. I would request you to close this issue
