### ISSUE TITLE
add supports multiple folders path as pylama input 

### ISSUE THREAD

**Issue by luzfcb** [klen/pylama#38]
flake8 supports multiple folders as input. this is very useful if you have several directories on the root directory

```
root_directory:
     pylama.ini
     setup.cfg
     setup.py
     app1/
     app2/
     app3/
```

It would be nice if I could run:

```
pylama app1 app2 app3
```

instead of

```
pylama app1 
pylama app2 
pylama app3 
```

**Comment by luzfcb** [comment]
@klen Thanks 

predicting future problems, there is some test with directories names that contain non ASCII characters?

**Comment by klen** [comment]
Nothing for now.

**Comment by fizyk** [comment]
this issue caused #46 install_hook still relies on a single path, while here we repalce it with paths.
