### ISSUE TITLE
New configuration option `paths` not usable from .ini configuration file

### ISSUE THREAD

**Issue by deuxpi** [klen/pylama#44]
We are currently (ab)using the `path` configuration option to define the top-level directory of the source code that should be scanned (best reason is to be more robust in the context of a continuous integration tool). Since the change in commit 7390602899d4a710ad9155f7b728c5901c0d4f74 the value returned by ArgumentParser is probably a list, but ConfigParser will still return a single string.

What's the right solution? Should we go back to skip all possible directories by hand (which is actually the only documented method) or attempt to fix this issue (which is roughly checking if the configuration argument is a string and `split` it)?

**Comment by klen** [comment]
Thank you for the feedback. I've added a small fix for that.
