### ISSUE TITLE
eradicate support

### ISSUE THREAD

**Issue by aequitas** [klen/pylama#50]
I'm currently missing this from pylama: https://pypi.python.org/pypi/eradicate

Might be a nice addition. Would you suggest adding it in pylama or a separate linter?
##

**Comment by reebr** [comment]
@orsinium @klen How can I disable this linter from command line(from tox, to be more specific)?
I've tried this:
```
pylama -i E800
``` 
But does not work.

**Comment by orsinium** [comment]
I'll check this way today. As temporary solution you can explicitly specify list of linters and except eradicate from it: `--linters=pyflake,codestyle,...`
