### ISSUE TITLE
Fail if a configured linter is not found

### ISSUE THREAD

**Issue by aequitas** [klen/pylama#52]
If a linter is listed in the configuration (eg: isort) pylama should fail if the linter is not found instead of giving only a warning: https://github.com/klen/pylama/blob/4e1994af951266467585b4fead84ecd5afca5c53/pylama/config.py#L68

This could be implemented as a setting to enforce or not enforce.
##

**Comment by mzfr** [comment]
@aequitas this is fixed now. Can you please close the issue.
