### ISSUE TITLE
Clarify license for Debian packaging

### ISSUE THREAD

**Issue by czchen** [klen/pylama#64]
Currently I am working on creating Debian package for pylama (https://bugs.debian.org/779449). However, the content of `pylama/__init__.py` is confused. The comment string says it is BSD license, but the LICENSE file is LGPL-3+.

```
    """
Code audit tool for python.
:copyright: 2013 by Kirill Klenov.
:license: BSD, see LICENSE for more details.
"""

__version__ = "7.0.9"
__project__ = "pylama"
__author__ = "Kirill Klenov <horneds@gmail.com>"
__license__ = "GNU LGPL"
```

Please help to clarify the actual license of this package by removing other license name/text in pylama so that we can work on Debian packaging, thanks.
##

**Comment by czchen** [comment]
@klen 

Can you help to clarify the license of `pylama/__init__.py`. Is it BSD or LGPL?

We want to provide `pylama` into Debian, and this is the only thing we need to fix before uploading.

**Comment by dotlambda** [comment]
I'd like to know that as well!

**Comment by susam** [comment]
Here is the commit history details regarding the licensing terms:

- Commit f6f4aab6 (2012-08-17) is the initial commit that shows that the project was originally licensed under GNU LGPL.
- Commits b1b10d14 (2013-05-21), 868b5337 (2013-06-06) and dcb35e46 (2013-08-07) mention BSD license.
- Commit a6ce4655 (2013-06-06) shows the intention of moving from GNU LGPL to BSD license.
- Commit 4f13f63a (2014-06-30) mentions GNU LGPL in the classifiers metadata.

In the latest `master` branch (at commit c38d598):

- Files `LICENSE` and `setup.py` mention GNU LGPL only.
- Files `docs/index.rst`, `pylama/libs/inirama.py`, and `README.rst` mention BSD license only.
- File `pylama/__init__.py` mentions both BSD license and GNU LGPL.

The project was originally licensed under GNU LGPL but later the author appears to have an intention of moving to BSD license. While there are several commits that provide evidence in favour of this conclusion, commit 4f13f63a contradicts this conclusion. The only place in the project that attempts to communicate the license explicitly to users or readers is `README.rst` which mentions:

> Licensed under a BSD license.

It is unclear which BSD license (BSD-3-Clause or BSD-2-Clause) is meant here.

Here is Debian's interpretation of the licensing terms (quoting from `/usr/share/doc/pylama/copyright` of Debian GNU/Linux 9 (stretch)):

    Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
    Upstream-Name: pylama
    Source: https://github.com/klen/pylama

    Files:     *
    Copyright: 2013 copyright Kirill Klenov <horneds@gmail.com>
    License:   LGPL-3+

    Files:     pylama/__init__.py
    Copyright: 2013 copyright Kirill Klenov <horneds@gmail.com>
    License:   LGPL-3+ or BSD-3-clause

    Files:     pylama/libs/inirama.py
    Copyright: 2013 copyright Kirill Klenov <horneds@gmail.com>
    License:   BSD-3-clause

    Files:     debian/*
    Copyright: ChangZhuo Chen (陳昌倬) <czchen@debian.org>
    License:   LGPL-3+

**Comment by honzajavorek** [comment]
@klen No update about this? LGPL-3+ and BSD-3-clause is a very big difference.

**Comment by klen** [comment]
From the version 8.0.0+ Pylama has the MIT license.
