### ISSUE TITLE
Results with pyflakes are different for each execution

### ISSUE THREAD

**Issue by pchomik** [klen/pylama#67]
My environment:

```
* Python 3.5.1
* pylama 7.0.9
* pylama-pylint 2.2.1
* pylint 1.5.4
```

My Test:

```
from os import path


def main() :
    """Some docstring."""
    if path.exists('/tmp'):
        return True



if __name__ = '__main__':
    main()

```

Executed command:

```
pylama -l mccabe,pyflakes,pylint,pep8,pep257 -F --sort E,W,D -f pep8 test.py
```

Expected result:

```
test.py:11:0: E0001 invalid syntax [pylint]
test.py:11:13: invalid syntax [pyflakes]
test.py:1:1: D100: Missing docstring in public module [pep257]
test.py:4:11: E203 whitespace before ':' [pep8]
test.py:11:1: E303 too many blank lines (3) [pep8]
```

Real result:
Set of entries from expected result. Very rarely I'm able to see all expected results. Problem disappears when pyflakes plugin is disabled.
##

**Comment by mzfr** [comment]
@pchomik I tested it and it seems to work fine I am getting
```
test.py:1:1: D100 Missing docstring in public module [pep257]
test.py:4:1: D401 First line should be in imperative mood; try rephrasing (found 'Some') [pep257]
```
in both the cases i.e with or without the pyflakes.

If you're testing the above example then notice that there's only a single `=` instead of having `==` in line `if __name__ = __main__:`

**Comment by klen** [comment]
Doesn't appear in the latest version.
