### ISSUE TITLE
Radon support?

### ISSUE THREAD

**Issue by italomaia** [klen/pylama#71]
What about adding radon support for code metrics?
##

**Comment by blueyed** [comment]
What do you mean exactly?
I think you are referring to http://radon.readthedocs.io/en/latest/intro.html, where only the Cyclomatic Complexity is included currently, right?
What should be added additionally?

**Comment by blueyed** [comment]
Ah, b99f1da was added later.
So this issue might be closed then?!

**Comment by imaia** [comment]
I believe so.

**Comment by mzfr** [comment]
@italomaia This issue is resolved, I think you can close the issues
