### ISSUE TITLE
Weird pylint format / default with all info

### ISSUE THREAD

**Issue by blueyed** [klen/pylama#73]
What is the "pylint" format based on?

The old default for pylint itself was "pylint --msg-template='{msg_id}:{line:3d},{column}: {obj}: {msg}'" and now is "{C}:{line:3d},{column:2d}: {msg} ({symbol})" (https://docs.pylint.org/en/1.6.0/output.html).

I would like to use pylama's pylint format, but it is missing the column.

```python
    pattern = "%(filename)s:%(lnum)s:%(col)s: %(text)s"
    if options.format == 'pylint':
        pattern = "%(filename)s:%(lnum)s: [%(type)s] %(text)s"
```

What do you think about specifying `--pattern`?
And what about a default format that includes all information? (with type and col) :)

**Comment by blueyed** [comment]
"pylint" seems to be derived from pylint's "parseable" format:

> {path}:{line}: [{msg_id}({symbol}), {obj}] {msg}

?

**Comment by klen** [comment]
Hello, historically I'd used this format for Jenkins plugin. Thank you for PR.
